-- MySQL Script generated by MySQL Workbench
-- Thu Nov  8 18:55:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS `babyLife` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `babyLife`;

 DROP USER `sistemaweb`@`localhost`; 
 CREATE USER `sistemaweb`@`localhost` identified by "123456"; 
GRANT ALL PRIVILEGES ON babyLife.* TO `sistemaweb`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `babyLife`.`usuarios_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`usuarios_master` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`bebe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`bebe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `usuarios_master_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bebe_usuarios_master1`
    FOREIGN KEY (`usuarios_master_id`)
    REFERENCES `babyLife`.`usuarios_master` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `medico` VARCHAR(45) NOT NULL,
  `observacao` TEXT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_consultas_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`pesoAltura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`pesoAltura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` VARCHAR(7) NOT NULL,
  `altura` VARCHAR(7) NOT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pesoAltura_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`banhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`banhos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_banhos_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`alimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`alimentacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_alimentacoes_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`fraldas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`fraldas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_fraldas_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`sonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`sonos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario_inicio` VARCHAR(45) NOT NULL,
  `horario_fim` VARCHAR(45) NOT NULL,
  `observacao` TEXT NULL,
  `bebe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sonos_bebe1`
    FOREIGN KEY (`bebe_id`)
    REFERENCES `babyLife`.`bebe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


-- -----------------------------------------------------
-- Table `babyLife`.`usuarios_secundarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babyLife`.`usuarios_secundarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `usuarios_master_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_secundarios_usuarios_master`
    FOREIGN KEY (`usuarios_master_id`)
    REFERENCES `babyLife`.`usuarios_master` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Innodb;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
